init post card
JesusFilm/Ark pull request #2
Opened 2021-04-27 18:49 UTC by gdub01

2021-04-29 03:16 UTC, tataihono commented
@gdub01 I've added in codecoverage. If you can bump it to 100% should be good for review.

2021-04-29 03:58 UTC, tataihono requested changes
You should do union types based on your variants.

```ts
type NetworkLoadingState = {
  state: "loading";
};
type NetworkFailedState = {
  state: "failed";
  code: number;
};
type NetworkSuccessState = {
  state: "success";
  response: {
    title: string;
    duration: number;
    summary: string;
  };
};
// Create a type which represents only one of the above types
// but you aren't sure which it is yet.
type NetworkState =
  | NetworkLoadingState
  | NetworkFailedState
  | NetworkSuccessState;
```

This way the component user will know which props they need to provide dependant on which variant they are using. It's a really cool use of typescript to make sure the right props are being passed.

2021-04-29 03:58 UTC, tataihono commented on src/elements/post-card/post-card.tsx
> +  publishedAt?: string;
I am wondering if this should be an iso8601 timestamp as opposed to a string.

This raises a query though about localization and our thoughts about where that data should be stored.

2021-04-29 03:58 UTC, tataihono commented on src/elements/post-card/post-card.tsx
> +type variant = 'hero' | 'premiere' | 'item' | 'card' | 'quote'
default should be an option here.
```suggestion
type variant = 'hero' | 'premiere' | 'item' | 'card' | 'quote' | 'default'
```

2021-04-29 03:58 UTC, tataihono commented on src/elements/post-card/post-card.tsx
> +  variant
```suggestion
  variant = 'default'
```

2021-04-29 03:58 UTC, tataihono commented on src/elements/post-card/post-card.tsx
> +  const withDefault = variant || 'default'
remove this in favor of a default string
```suggestion
```

2021-04-29 03:58 UTC, tataihono commented on src/elements/post-card/post-card.tsx
> +        }[withDefault]
```suggestion
        }[variant]
```

2021-04-29 03:58 UTC, tataihono commented on src/elements/post-card/post-card.tsx
> +    <React.Fragment>
```suggestion
    <>
```

2021-04-29 03:58 UTC, tataihono commented on src/elements/post-card/post-card.tsx
> +    </React.Fragment>
```suggestion
    </>
```

2021-04-29 15:08 UTC, gdub01 commented on src/elements/post-card/post-card.tsx
> +  publishedAt?: string;
Agreed. 
Data coming back from a backend may or may not be iso8601... so the data fetcher has to potentially convert the date. 
Probably the post card should dictate the format of the string. Either 5 minutes ago or 2:13 April 28 2021 or whatever it is.. post card should probably make it consistent which means it shouldn't be a string. 
cldr data can automatically localize things like datetime.. we could consider pulling in a lib that deals with that. 
That being the case, a bcp47 code or something would be required if the component is run on the server, and default to english? 
If the component is run on a client, it could make bcp47 optional and grab the code from the browser maybe.

2021-05-05 01:54 UTC, tataihono requested changes
great progress on those union types. Some more changes to look into.

2021-05-05 01:54 UTC, tataihono commented on src/elements/post-card/post-card.tsx
> +export type PostCardProps = HeroProps | PremiereProps | ItemProps | QuoteProps & TimeAgoProps | DefaultProps & TimeAgoProps
the parent shouldn't be concerned with modifying the underlying types.
```suggestion
export type PostCardProps = HeroProps | PremiereProps | ItemProps | QuoteProps | DefaultProps
```

2021-05-05 01:54 UTC, tataihono commented on src/elements/post-card/variants/default.tsx
> +  style: 'default',
this prop and in all other prop types should be called variant to match how Material-UI implements variable naming.

2021-05-05 01:54 UTC, tataihono commented on src/elements/post-card/variants/default.tsx
> +  /** Image source url */
please monitor caps.

2021-05-05 01:54 UTC, tataihono commented on src/elements/post-card/variants/default.tsx
> +}: DefaultProps & TimeAgoProps) {
I think there should just be a TimeAgoProps prop. See the ListboxProps example on the Autocomplete component from Material UI. This will allow automatic support for future props added to the TimeAgoProps defintion.

2021-05-05 01:54 UTC, tataihono commented on src/elements/post-card/variants/default.tsx
> +        <Grid item>
This grid item should be conditional on the excerpt being present.

2021-05-05 01:54 UTC, tataihono commented on src/elements/post-card/variants/default.tsx
> +          <img src={src} className={classes.image} />
what happens to this is src is not provided. In the type it is optional.

2021-05-05 01:54 UTC, tataihono commented on src/elements/post-card/variants/hero.tsx
> +                      onClick={() => onClick?.()}
```suggestion
                      onClick={onClick}
```

the function null check already happens on line 86.

2021-05-05 01:54 UTC, tataihono commented on src/elements/post-card/variants/hero.tsx
> +                      Read Story
thoughts on internationalization here?

2021-05-05 01:54 UTC, tataihono commented on src/elements/post-card/variants/hero.tsx
> +                <Grid item>
should be optional based on category

2021-05-05 01:54 UTC, tataihono commented on src/elements/post-card/variants/hero.tsx
> +                <Grid item>
should be optional based on excerpt

2021-05-05 01:54 UTC, tataihono commented on src/elements/post-card/variants/item.tsx
> +          <Grid item>
should be optional based on author

2021-05-05 01:54 UTC, tataihono commented on src/elements/post-card/variants/premiere.tsx
> +        <Grid item>
what happens here if source is null

2021-05-05 01:54 UTC, tataihono commented on src/elements/post-card/variants/premiere.tsx
> +        <Grid item>
optional base on excerpt

2021-05-05 01:54 UTC, tataihono commented on src/elements/post-card/variants/quote.tsx
> +}: QuoteProps & TimeAgoProps) {
should have TimeAgoProps prop instead of merging QuoteProps and TimeAgoProps.

2021-05-05 01:54 UTC, tataihono commented on src/elements/post-card/post-card.spec.tsx
> +  it('should render with the correct text', () => {
I think this spec should be broken down into different files for each sub-component.

2021-05-05 01:54 UTC, tataihono commented on src/elements/time-ago/time-ago.docs.mdx
> +A simple TimeAgo component with some text
add better description

2021-05-10 13:38 UTC, gdub01 commented on src/elements/post-card/variants/hero.tsx
> +                      Read Story
https://react.i18next.com seems to be the most popular.
 
Would you want that integrated in this PR or leave Read Story as is for now and do a separate PR for translations?

It's going to be tough because there's the concept of backends/translations and we're a component lib only.. so do we let the user of the lib provide the translation? 

There's also the idea of dynamic fetching of translations and fetching them once at compile time.. so we'd likely have to pick. 

On top of that users of our lib would probably have their own int'l needs and have their own backends.

2021-05-14 03:49 UTC, tataihono requested changes
thanks for sorting this. Let me know what you think about the proposed changes.

2021-05-14 03:49 UTC, tataihono commented on src/elements/post-card/post-card.composition.tsx
> +  />
If someone added props to `<HeroPostCard>` they should override the ones you've set here by default. This should be the case for all the following methods.

```suggestion
    {...props}
  />
```

2021-05-14 03:49 UTC, tataihono commented on src/elements/post-card/post-card-default.spec.tsx
> +  DefaultPostCard
sorry about this. I was thinking about the variant components having their own folder with the test next to them. Then importing the variant component directly.

```
post-card/
	post-card.tsx
	post-card.[docs,spec,composition].tsx
	variants/
		index.ts
		default/
			default.tsx
			default.spec.tsx
			index.ts
		...
```

It's a bit more verbose but I think the added complexity here will scale well with future components.

2021-05-14 03:49 UTC, tataihono commented on src/elements/post-card/post-card.spec.tsx
> +    const handleClick = jest.fn()
you don't have to have this handler mocked everywhere since you are not actually testing to see if was called in this test.

2021-05-14 03:49 UTC, tataihono commented on src/elements/post-card/post-card.spec.tsx
> +  it('should render with the correct text', () => {
this file should be testing to see if the correct variant is being loaded based on the props.

2021-05-17 17:59 UTC, gdub01 commented on package.json
> +    "timeago.js": "^4.0.0",
I can swap it for date-fns... but I'm confused here.. date-fns would also be a dependency addition would it not?

2021-05-19 20:33 UTC, gdub01 commented on package.json
> +    "timeago.js": "^4.0.0",
@tataihono ^^

2021-05-25 02:45 UTC, tataihono submitted a review, later dismissed
I am happy with this. Just wondering your thoughts about using compositions in tests. It does make them difficult to follow and may make the tests brittle if we need to update the compositions.

2021-06-02 23:10 UTC, tataihono approved these changes

2021-06-02 23:18 UTC, merged