ARK-39 Core Embed Component
JesusFilm/Ark pull request #32
Opened 2021-07-08 02:35 UTC by GeronimoJohn

- Created the core embed component
- Created embed variants to support iframe, vimeo, and youtube videos
- Created a variant to show unsupported embed videos
- The embed component currently only support videos

2021-07-08 03:46 UTC, tataihono requested changes
good first pass. A number of things to work on here to tidy up edge cases. Thanks for your work!

2021-07-08 03:46 UTC, tataihono commented on .bitmap
> +        "version": "0.0.1",
somethings wrong here. This is already at version 0.0.2. Can you try revert this file to main and then running the `bit add --soft` command again.

2021-07-08 03:46 UTC, tataihono commented on src/elements/block/blockData.ts
> +      url: 'https://youtu.be/UGFCbmvk0vo',
any chance you can also test the other youtube link format too?

2021-07-08 03:46 UTC, tataihono commented on src/elements/block/core-embed/core-embed.spec.tsx
> +      <Youtube
This file should not test the subcomponents.

2021-07-08 03:46 UTC, tataihono commented on src/elements/block/core-embed/core-embed.tsx
> +      return <Default attributes={attributes} />
This should be tested.

2021-07-08 03:46 UTC, tataihono commented on src/elements/block/core-embed/embed/default/default.spec.tsx
> +it('should render with the right text', () => {
you need to test that the component is outputting the providerNameSlug here so we can troubleshoot this in future.

2021-07-08 03:46 UTC, tataihono commented on src/elements/block/core-embed/embed/iframe/iframe.spec.tsx
> +})
Can you move all your tests into describe blocks like so? This means in the test interface the component name is displayed on failure.

```suggestion
describe('Iframe', () => {
  it('should render the embeded video', () => {
    const { getByTestId } = render(
      <Iframe
        attributes={{
          url: 'https://www.youtube.com/embed/UGFCbmvk0vo',
          providerNameSlug: 'embed-handler'
        }}
      />
    )
    expect(getByTestId('embed-handler').getAttribute('src')).toEqual(
      'https://www.youtube.com/embed/UGFCbmvk0vo'
    )
  })
})
```

2021-07-08 03:46 UTC, tataihono commented on src/elements/block/core-embed/embed/iframe/iframe.tsx
> +export function Iframe({ attributes }: IframeProps) {
```suggestion
export function Iframe({ attributes: { providerNameSlug, url } }: IframeProps) {
```

if you want shorthand access to the params. Otherwise you are repeating attributes each time you are trying to access sub-items.

2021-07-08 03:46 UTC, tataihono commented on src/elements/block/core-embed/embed/youtube/youtube.tsx
> +function extractYoutubeID(url): string {
what happens if this returns undefined? I think as it is it will try and render ``https://www.youtube.com/embed/undefined`. Can you catch this and render something like your default component.

2021-07-14 03:40 UTC, tataihono requested changes
got a few changes for you 👯

2021-07-14 03:40 UTC, tataihono commented on src/elements/block/core-embed/embed/error/error.tsx
> +  attributes: Attributes
drop this

2021-07-14 03:40 UTC, tataihono commented on src/elements/block/core-embed/embed/error/error.tsx
> +        data-testid={providerNameSlug}>
this isn't needed

2021-07-14 03:40 UTC, tataihono commented on src/elements/block/core-embed/embed/error/error.tsx
> +export function Error({
this can just be a component under block instead of being something specific to just core-embed

2021-07-14 03:40 UTC, tataihono commented on src/elements/block/core-embed/embed/youtube/youtube.spec.tsx
> +  it('should render the embeded video', () => {
there should be a test in here for the purposes of testing the error

2021-07-14 03:40 UTC, tataihono commented on src/elements/block/core-embed/embed/youtube/youtube.tsx
> +  switch (youtubeId) {
this doesn't need a switch. This should just be an if statement.

2021-07-14 03:40 UTC, tataihono commented on src/elements/block/core-embed/embed/vimeo/vimeo.tsx
> +  switch (vimeoId) {
opt for an if statement

2021-07-14 03:40 UTC, tataihono commented on src/elements/block/core-embed/embed/vimeo/vimeo.tsx
> +          subtitle={vimeoUrl}
this should be `attributes.url`

2021-07-14 03:40 UTC, tataihono commented on src/elements/block/core-embed/embed/youtube/youtube.tsx
> +          subtitle={youtubeUrl}
```suggestion
          subtitle={attributes.url}
```

2021-07-14 03:40 UTC, tataihono commented on src/elements/block/core-paragraph/core-paragraph.tsx
> +export function CoreParagraph({ attributes, __typename }: CoreParagraphProps) {
this __typename is an unused value.
```suggestion
export function CoreParagraph({ attributes }: CoreParagraphProps) {
```

2021-07-14 03:40 UTC, tataihono commented on src/elements/post-card/variants/default/default.tsx
> -        {/* <Grid item>
drop comment

2021-07-14 20:31 UTC, GeronimoJohn commented on src/elements/block/core-embed/embed/error/error.tsx
> +        data-testid={providerNameSlug}>
Do you mean the whole thing? Or just one of the elements in here?

2021-07-14 20:57 UTC, GeronimoJohn commented on src/elements/block/core-embed/embed/youtube/youtube.spec.tsx
> +  it('should render the embeded video', () => {
added some test for the error. Also added some for error on the vimeo component

2021-07-14 22:45 UTC, tataihono approved these changes

2021-07-14 22:45 UTC, merged