ARK-28 Post Footer Component
JesusFilm/Ark pull request #34
Opened 2021-07-12 03:53 UTC by GeronimoJohn

- Created the post footer biography component
- Putting a pause on implementing the blog list for the footer after the biography

2021-07-14 03:42 UTC, tataihono commented
@GeronimoJohn these changes probably could have been based off main since its relatively disconnected from your core-embed changes.

2021-07-16 02:55 UTC, tataihono requested changes
good work. some things to fix up.

2021-07-16 02:55 UTC, tataihono commented on src/elements/post/post.tsx
> +    author: AuthorNode
can probably drop this since post footer props is handling this.

2021-07-16 02:55 UTC, tataihono commented on src/elements/post/footer/footer.tsx
> +        His Word in Yours
this should use useTranslation hook for i18n.

2021-07-16 02:55 UTC, tataihono commented on src/elements/post/footer/footer.tsx
> +        READ MORE BLOGS & STORIES
this should use useTranslation hook for i18n. This should also rely on CSS for upcasing.

2021-07-16 02:55 UTC, tataihono commented on src/elements/post/footer/footer.tsx
> +              alt="Josh McDowell"
this needs to be dynamic.

2021-07-16 02:55 UTC, tataihono commented on src/elements/post/footer/footer.tsx
> +  blogs?: BlogNode
drop this for now.

2021-07-16 02:55 UTC, tataihono commented on src/elements/post/footer/footer.spec.tsx
> +    expect(getByTestId('user')).toBeInTheDocument()
not sure what this is testing. You should be testing for a link at this point.

2021-07-19 19:42 UTC, tataihono submitted a review, later dismissed
some changes needed around author link.

2021-07-19 19:42 UTC, tataihono commented on src/elements/post/footer/footer.tsx
> +              </AuthorLink>
add `import { Link } from '@material-ui/core'`

then do something like:

```suggestion
          <Link component={AuthorLink} href={author.node.slug}>
            {author.node.name}
          </Link>
```

See PostCard premiere variant for details.

2021-07-19 19:42 UTC, tataihono commented on src/elements/post/footer/footer.tsx
> +}
`slug` should be added here

2021-07-19 21:16 UTC, GeronimoJohn commented on src/elements/post/footer/footer.tsx
> +              </AuthorLink>
Kept the className

2021-07-20 20:54 UTC, tataihono submitted a review, later dismissed
can you revisit this PR to pull in the post-list compound component?

2021-07-22 00:27 UTC, tataihono submitted a review, later dismissed
pleaes tidy up the .bitmap file and this should be good to go!

2021-07-22 00:27 UTC, tataihono commented on .bitmap
> +        "rootDir": "src/elements/block",
any idea why this is still in here yet the conversation is resolved?

2021-07-22 04:50 UTC, tataihono submitted a review, later dismissed
categoryId should be removed

2021-07-22 04:50 UTC, tataihono commented on src/elements/post/post.tsx
> +  categoryId: number
where did this come from? This should be slug I think.

2021-07-27 01:02 UTC, tataihono approved these changes

2021-07-27 01:19 UTC, merged