ARK-42 Core Arclight Component
JesusFilm/Ark pull request #35
Opened 2021-07-13 21:57 UTC by GeronimoJohn

- Found a way to create a custom block on Wordpress through the plugin Lazyblocks - this custom block is called Arclight
- The custom block arclight renders arclight videos on Wordpress and enables us to pull data from GraphQL
- Created a component for Arclight

2021-07-14 03:41 UTC, tataihono commented
@GeronimoJohn can you write `depends on #32` so that its clear what PR this is connected with?

2021-07-15 05:19 UTC, tataihono requested changes
there are a bunch of out-of-scope changes in this PR. Please remove them thanks!

2021-07-15 05:19 UTC, tataihono commented on src/elements/block/core-embed/embed/error/error.spec.tsx
> +import React from 'react'
this file needs to go.

2021-07-15 05:19 UTC, tataihono commented on src/elements/block/core-embed/embed/error/error.tsx
> +import React from 'react'
this file needs to go.

2021-07-15 05:19 UTC, tataihono commented on src/elements/block/core-embed/embed/error/index.ts
> +export { Error } from './error'
this file needs to go.

2021-07-15 05:19 UTC, tataihono commented on src/elements/block/core-paragraph/core-paragraph.tsx
> +export function CoreParagraph({ attributes, __typename }: CoreParagraphProps) {
unnecessary change

2021-07-16 02:56 UTC, tataihono requested changes
there are a number of unrelated changes in this PR. can you please back them out.

2021-07-16 02:56 UTC, tataihono commented on src/elements/block/core-arclight/core-arclight.spec.tsx
> +it('should render with the correct text', () => {
this is not a good summary of what this test is doing.

2021-07-19 03:55 UTC, tataihono requested changes
still have a bunch of unrelated changes in this branch @GeronimoJohn

2021-07-19 04:41 UTC, GeronimoJohn commented
Too many out of scope changes in this branch. Will be replaced by a new branch

2021-07-19 04:41 UTC, closed without merging