ARK-45 Elements Mission
JesusFilm/Ark pull request #39
Opened 2021-07-15 23:35 UTC by GeronimoJohn

- Create the elements/mission component
- Do not add the background photo as seen on the JFP Figma
- Merge the main branch to this branch to ensure its updated
- replaces https://github.com/JesusFilm/Ark/pull/38

2021-07-16 03:00 UTC, tataihono requested changes
hmm. most of this component needs to be refactored sorry.

2021-07-16 03:00 UTC, tataihono commented on src/elements/mission/mission.spec.tsx
> +  const { getByText } = render(<BasicMission />)
tests should avoid using compositions since their underlying data can change causing the test to break.

2021-07-18 22:45 UTC, GeronimoJohn commented on src/elements/mission/mission.tsx
> +    color: '#EF3340'
I did but theme.palette.primary.main is giving back the color blue instead. Though in the theme.ts file it is set to the red that we want.

<img width="1380" alt="Screen Shot 2021-07-19 at 10 42 08 AM" src="https://user-images.githubusercontent.com/53248335/126084326-068bbb07-ef03-40d3-b6ee-dd5db4c4cb22.png">

2021-07-19 03:52 UTC, tataihono submitted a review, later dismissed

2021-07-19 03:52 UTC, tataihono commented on src/elements/mission/mission.tsx
> +  const { t } = useTranslation()
add a namespace here for now.
```suggestion
  const { t } = useTranslation('mission')
```

2021-07-19 19:36 UTC, tataihono requested changes

2021-07-19 19:36 UTC, tataihono commented on src/elements/mission/mission.docs.mdx
> +<Mission text="Together, we will share Jesus with 5 billion people by 2025. This is where you can read and share stories of how God's amazing love and power is reaching people through churches, organ
```suggestion
<Mission />
```

2021-07-19 19:36 UTC, tataihono commented on src/elements/mission/mission.docs.mdx
> +labels: ['React', 'typescript', 'block']
```suggestion
labels: ['React', 'Typescript', 'Mission']
```

2021-07-20 20:55 UTC, tataihono approved these changes

2021-07-20 21:59 UTC, merged