ARK-44 List Header and ARK-45 Author List
JesusFilm/Ark pull request #41
Opened 2021-07-19 00:59 UTC by GeronimoJohn

- Create list-header component
- Create components folder and move author-list into this folder
- Integrate list-header to author-list
- Refactor author-list props
     - Add AuthorLink, title, onSeeAllClick props

2021-07-19 19:44 UTC, tataihono requested changes
remove onClick from author list in favour of using AuthorLink prop. Also should use Link from material-ui/core. Happy to answer questions on how to do this.

2021-07-20 20:53 UTC, tataihono submitted a review, later dismissed

2021-07-20 20:53 UTC, tataihono commented on src/compounds/author-list/author-list.composition.tsx
> +      title=""
this shouldn't be needed right?

2021-07-20 20:53 UTC, tataihono commented on src/compounds/author-list/author-list.spec.tsx
> +        title=""
should remove this

2021-07-20 20:53 UTC, tataihono commented on src/compounds/author-list/author-list.spec.tsx
> +    expect(getByText('Tez Brooks')).toBeInTheDocument()
this should also test that the header is not visible right?

2021-07-20 20:53 UTC, tataihono commented on src/elements/author-card/author-card.docs.mdx
> +        url: ''
can you put the image back for this one?

2021-07-20 20:53 UTC, tataihono commented on src/compounds/author-list/author-list.tsx
> +  authors: AuthorCardProps[]
this needs to just be the data for the author card.

```
  authors: {
    nodes: Author[]
  }
```

AuthorLink needs to be passed as a separate prop then passed down to the AuthorCard seperately. See the PremierePostListProps in Post List compound component for an example.

2021-07-20 20:53 UTC, tataihono commented on src/elements/author-card/author-card.composition.tsx
> +          url: ''
you should just be able to drop the avatar attribute right?

2021-07-20 20:53 UTC, tataihono commented on src/elements/author-card/author-card.docs.mdx
> +A component that display a single author with name, description and profile image.
```suggestion
A component that displays a single author with a name, description and profile image. 
```

2021-07-20 20:53 UTC, tataihono commented on src/elements/author-card/author-card.docs.mdx
> +### Using props to customize the text
```suggestion
### Using props to customize the author
```

2021-07-20 20:53 UTC, tataihono commented on src/elements/list-header/list-header.docs.mdx
> +A component that renders the header of a list it's under in
```suggestion
A component that renders a header for a list of items
```

2021-07-20 20:53 UTC, tataihono commented on src/elements/list-header/list-header.docs.mdx
> +### Using props to customize the text
```suggestion
### Using props to customize the title
```

2021-07-20 20:53 UTC, tataihono commented on src/elements/list-header/list-header.tsx
> +                SEE ALL
translate this string

2021-07-20 20:53 UTC, tataihono commented on src/elements/list-header/list-header.tsx
> +    color: '#EE3441',
I don't think we should set this here. Use one of the palette colors from the theme.

2021-07-20 20:53 UTC, tataihono commented on src/elements/list-header/list-header.tsx
> +              <Typography variant="body2" className={classes.seeAll}>
This should be a button with variant link.

2021-07-20 20:53 UTC, tataihono commented on src/elements/post/post.tsx
> -import { AuthorCard } from '@jesus-film/ark.elements.author-card'
These changes are irrelevant to this PR.

2021-07-22 00:59 UTC, GeronimoJohn commented on src/elements/list-header/list-header.tsx
> +              <Typography variant="body2" className={classes.seeAll}>
When you say varian link. Do you mean like create a custom link like author link?

2021-07-27 01:01 UTC, tataihono requested changes

2021-07-28 21:45 UTC, tataihono approved these changes

2021-07-28 21:48 UTC, merged